/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hermes.components.HMDesktop;

import javax.swing.JToolBar;

/**
 *
 * @author iury
 */
public class HMToolBar extends JToolBar {

    /**
     * Creates new form HMToolBar
     */
    public HMToolBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnPropriedades = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnBugReport = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setBackground(new java.awt.Color(224, 237, 255));
        setFloatable(false);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_add.png"))); // NOI18N
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setMaximumSize(new java.awt.Dimension(80, 71));
        btnNovo.setMinimumSize(new java.awt.Dimension(80, 71));
        btnNovo.setOpaque(false);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        add(btnNovo);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open_folder.png"))); // NOI18N
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setMaximumSize(new java.awt.Dimension(80, 71));
        btnAbrir.setMinimumSize(new java.awt.Dimension(80, 71));
        btnAbrir.setOpaque(false);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnAbrir);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_1.png"))); // NOI18N
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setMaximumSize(new java.awt.Dimension(80, 71));
        btnExcluir.setMinimumSize(new java.awt.Dimension(80, 71));
        btnExcluir.setOpaque(false);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnExcluir);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setMaximumSize(new java.awt.Dimension(80, 71));
        btnSalvar.setMinimumSize(new java.awt.Dimension(80, 71));
        btnSalvar.setOpaque(false);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        add(btnSalvar);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        btnPesquisar.setFocusable(false);
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisar.setMaximumSize(new java.awt.Dimension(80, 71));
        btnPesquisar.setMinimumSize(new java.awt.Dimension(80, 71));
        btnPesquisar.setOpaque(false);
        btnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnPesquisar);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setMaximumSize(new java.awt.Dimension(80, 71));
        btnImprimir.setMinimumSize(new java.awt.Dimension(80, 71));
        btnImprimir.setOpaque(false);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnImprimir);

        btnPropriedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        btnPropriedades.setFocusable(false);
        btnPropriedades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPropriedades.setMaximumSize(new java.awt.Dimension(80, 71));
        btnPropriedades.setMinimumSize(new java.awt.Dimension(80, 71));
        btnPropriedades.setOpaque(false);
        btnPropriedades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnPropriedades);
        add(jSeparator1);

        btnBugReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        btnBugReport.setFocusable(false);
        btnBugReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBugReport.setMaximumSize(new java.awt.Dimension(80, 71));
        btnBugReport.setMinimumSize(new java.awt.Dimension(80, 71));
        btnBugReport.setOpaque(false);
        btnBugReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnBugReport);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnBugReport;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPropriedades;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
